@startuml
hide footbox

participant "jeuLaby:LabyJeu" as game
participant "laby:Labyrinthe" as laby
participant "monstres:ArrayList<Monstre>" as monstres
participant "heros:Heros" as heros
participant "monstre:Monstre" as monstre


game -> game: update(double, Clavier)
loop monstres
game -> monstres: get(i)
game <-- monstres
game -> laby: verifierPresenceMonstreCaseAdjacente(int, int)
game <-- laby

heros -> heros:attaquer(monstre)
end

@enduml